### ISSUE TITLE
Improve `inputPath`

### ISSUE THREAD

**Issue by nlemoine** [matteobertoldo/mjml-webpack-plugin#19]
**Context**

Some part of the `inputPath` is currently hard coded and can't be changed with arguments/options: `${that.inputPath}/**/*.mjml`

I'm using MJML in a Twig context and usually use this kind of file extension: `.mjml.twig`. Unfortunately, I can't compile them because the plugin forces the `.mjml` extension. 

I also prefix my template parts with an underscore: `_header.mjml` (sass way) but since the plugin doesn't provide control on the glob either, I can't exclude them with a custom glob like: `[^_]*.mjml`. Neither can I place them in separate folder, or it must be outsides of my `/templates/emails` scope.

**Describe the solution you'd like**

More freedom over the glob pattern used to collect files that should be compiled. Ideally removing the `/**/*.mjml` part.

**Describe alternatives you've considered**

Rename everything to `.mjml`, avoid underscores, sure this does work but since it's a webpack that being used by developers, I think people are enough skilled to provide their own glob.

**Comment by matteobertoldo** [comment]
Hi @nlemoine! sounds good 😊. I will arrange to release a fix for this in the next few days!

Thanks for the contribution.

**Comment by nlemoine** [comment]
Thanks for considering this 🙂

**Comment by matteobertoldo** [comment]
Hi @nlemoine i release the new version with the custom `glob` pattern supports! Cheers! 🍻

**Comment by nlemoine** [comment]
Thanks a lot @matteobertoldo ! 🙂
